#!/bin/sh

template_dir="$HOME/templates/latex/tex"

templates=($(ls -1 "$template_dir"))

echo "Available LaTeX templates:"
for i in "${!templates[@]}"; do
    echo "$(($i+1)). ${templates[$i]}"
done

read -p "Enter the template number: " template_number

if ! [[ "$template_number" =~ ^[0-9]+$ ]]; then
    echo "Invalid template number. Exiting."
    exit 1
fi

index=$(($template_number - 1))

if ! ((index >= 0 && index < ${#templates[@]})); then
    echo "Invalid template number. Exiting."
    exit 1
fi

template_name="${templates[$index]}"

template_path="$template_dir/$template_name"

read -p "Enter the name of the .tex file: " tex_file_name

mkdir -p "$tex_file_name/sections" "$tex_file_name/figures" "$tex_file_name/bib"

cp ~/templates/latex/tex/$template_name ./$tex_file_name/$tex_file_name.tex
cp ~/templates/latex/sections/preamble.tex "./$tex_file_name/sections/preamble.tex"
cp ~/templates/latex/figures/uts_logo.png "./$tex_file_name/figures/logo.png"
cp ~/templates/latex/figures/title_image.png "./$tex_file_name/figures/title_image.png"
cp ~/templates/latex/sections/titlepage.tex "./$tex_file_name/sections/titlepage.tex"

touch ./$tex_file_name/bib/bibliography.bib

if [ "$template_name" == "report" ] || [ "$template_name" == "article" ]; then
    read -p "Add a titlepage? (Y/n): " add_titlepage
    add_titlepage=${add_titlepage:-Y}  

    if [[ $add_titlepage == "y" || $add_titlepage == "Y" ]]; then
        read -p "Name the titlepage: " titlepage_name
        indented_titlepage_name=$(printf '\t\t\t%s' "$titlepage_name")
        sed -i "8s/.*/$indented_titlepage_name/" "./$tex_file_name/sections/titlepage.tex" 
        
        header_name="   \\\\lhead{$titlepage_name}"
        sed -i "59s|.*|$header_name|" "./$tex_file_name/sections/preamble.tex"
            
        read -p "What class is it for: " class_name
        indented_class_name=$(printf '\t\t\t%s' "$class_name")
        sed -i "30s/.*/$indented_class_name/" "./$tex_file_name/sections/titlepage.tex"
        
        read -p "Describe the project: " project_name
        indented_project_name=$(printf '\t\t\t%s' "$project_name")
        sed -i "28s/.*/$indented_project_name/" "./$tex_file_name/sections/titlepage.tex"
    fi
fi

if [ "$template_name" == "report" ] || [ "$template_name" == "article" ]; then
    read -p "Add a coversheet? (Y/n): " add_coversheet
    add_coversheet=${add_coversheet:-Y}  

    if [[ $add_coversheet == "y" || $add_coversheet == "Y" ]]; then

        coversheet_filename="./$tex_file_name/coversheet/uts_coversheet.tex"
        cp -r ~/.local/bin/tex-init/coversheet/ ./$tex_file_name/

        surname=$(sed -n '1p' ~/.local/bin/tex-init/coversheet.config)
        first_name=$(sed -n '2p' ~/.local/bin/tex-init/coversheet.config)
        email_address=$(sed -n '3p' ~/.local/bin/tex-init/coversheet.config)
        student_id=$(sed -n '4p' ~/.local/bin/tex-init/coversheet.config)
        data_entry_1="$ & $surname \\hspace{15pt} $first_name & $student_id \\\\"
        escaped_data_entry_1=$(echo "$data_entry_1" | sed 's/[&/\]/\\&/g')

        sed -i "31s/.*/$escaped_data_entry_1/" "$coversheet_filename" 
        sed -i "39s/.*/$email_address/" "$coversheet_filename" 

        read -p "Fill in non-personal details? (Y/n): " add_details

        add_details=${add_details:-Y}  
        if [[ $add_details == "y" || $add_details == "Y" ]]; then
            read -p "Enter class number and name: " class_name
            data_entry_1="$class_name & $surname \\hspace{15pt} $first_name & $student_id \\\\"
            escaped_data_entry_1=$(echo "$data_entry_1" | sed 's/[&/\]/\\&/g')

            sed -i "31s/.*/$escaped_data_entry_1/" "$coversheet_filename" 

            read -p "Enter tutor name: " tutor_name
            sed -i "53s/.*/$tutor_name/" "$coversheet_filename" 

            read -p "Enter tutorial group: " tutorial_group
            sed -i "57s/.*/$tutorial_group/" "$coversheet_filename"

            read -p "Enter due date: " due_date
            sed -i "61s/.*/$due_date/" "$coversheet_filename" 


            read -p "Enter assessment item number and title: " assessment_title
            sed -i "70s/.*/$assessment_title/" "$coversheet_filename" 
        fi

        cd "./$tex_file_name/coversheet/" 
        echo "Compiling coversheet..."
        pdflatex -shell-escape "./uts_coversheet.tex" > /dev/null
        cd ../..
        add_coversheet_text="\\\includepdf[pages=-]{./coversheet/uts_coversheet.pdf}"
        sed -i "8s|.*|$add_coversheet_text|" "./$tex_file_name/$tex_file_name.tex"
    fi
fi

cd "$tex_file_name"

echo -e "\nGenerating your $template_name..."

pdflatex -shell-escape "./$tex_file_name.tex" > /dev/null
bibtex ./$tex_file_name.aux > /dev/null
pdflatex -shell-escape "./$tex_file_name.tex" > /dev/null

sleep 0.5
zathura "./$tex_file_name.pdf" &
disown
$EDITOR "./$tex_file_name.tex"
